### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by Firesphere** [Spomky-Labs/u2f-php#15]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Version              | 1.x-dev

Any chance of this going stable any time soon? It looks interesting, but without a proper stable release, it's hard to consider it for production use.

**Comment by Spomky** [comment]
Hi,

I will mark this library as stable when the documentation will be available (at least first class definitions and examples).
It should be done by the end of the year.

**Comment by Spomky** [comment]
Hi,

I've [created a project](https://github.com/Spomky-Labs/u2f-php/projects/1) where all features/bugs sits before the first stable release of the library.

I now close this issue. Let's continue the discussion in each issue related to that project.
Feel free to open another issue if you think something is missing.
