### ISSUE TITLE
Yet another U2F library?

### ISSUE THREAD

**Issue by stephanvierkant** [Spomky-Labs/u2f-php#7]
https://github.com/Firehed/u2f-php
https://github.com/Yubico/php-u2flib-server

I've found two other libraries that provide the same FIDO U2F server protocol in PHP. What's the difference with those libraries?

**Comment by Spomky** [comment]
Hi,

That's a very interesting question.

First of all, I created that library to have a better understanding of the U2F protocol.
I prefer spending time to know how to communicate with these tokens than just include some other libraries in my projects (**if I don't know how it works, I don't use it**).

Second, I know that the library you mentioned do the job (and certainly better than I).
I just want to create another alternative and another way to communicate with those tokens using only immutable objects and thus improve the developper experience (what kind of argument is needed for [the method `getRegisterData`](https://github.com/Yubico/php-u2flib-server/blob/master/src/u2flib_server/U2F.php#L118)?).
It is also quite strange for me to have only [one class (500+ lines)](https://github.com/Yubico/php-u2flib-server/blob/master/src/u2flib_server/U2F.php) to handle both registration and authentication stages.

In any case, if you think this library can be enhanced by any means, just let me know.

*Note 1: I was not aware of Firehed/u2f-php. Looks great by the way.*
*Note 2: at the moment, this library should not be considered as stable.*

**Comment by stephanvierkant** [comment]
Creating a new library versus understanding and improving an existing library: an interesting and difficult choice ;).

I agree the Yubico library has some quality issues. As for the 500+ file (not just one class, but that makes it even worse), see https://github.com/Yubico/php-u2flib-server/pull/49. Not using PSR-4 in 2018 is quite a shame, to be honest.

I always hope we (as a PHP community) can create one high quality (in this case: U2F) library that fits all purposes, but understand that's not always possible.

**Comment by Spomky** [comment]
Unfortunatly, it is sometime hard to improve existing libraries.
I have [some personal experiences](https://github.com/FriendsOfSymfony/friendsofsymfony.github.io/issues/47) that failed.
Nevertheless, it did not stop me. The result is that I decided to create my own projects (e.g. [here](https://github.com/oauth2-framework) or [here](https://github.com/web-token)).

The next step for that library is to improve the registration step. At the moment, it is tightly coupled to the U2F_V2 version.  will add a way to support any other versions of the protocol. Any new version will be easier to add.

**Comment by Spomky** [comment]
Hi @stephanvierkant,

I will close that topic as already answered.
Before that, I would like to let you know that this library will also support the the [Webauthn](https://www.w3.org/TR/webauthn/) protocol.
I bought some FIDO2 keys and started my tests.

**Comment by Spomky** [comment]
Hi @stephanvierkant.

I’ve just seen a PR from @zae on the Yubico repository. It looks like lot of people are interested in a PSR2/4 PHP7 library for U2F.
That library works fine for the U2F protocol, but I need some feedback and help to continue my work regarding Webauthn.

Let me know if you have time test it or contribute to it.
